Add scan binaries template
FirelyTeam/azure-pipeline-templates pull request #16
Opened 2023-10-04 15:25 UTC by mmsmits

2023-10-04 15:57 UTC, marcovisserFurore requested changes
I think we can have 1 parameter less.

2023-10-04 15:57 UTC, marcovisserFurore commented on scanBinaries.yml
> +  directory: # directory where the zipfile is extracted
Is it really necessary that `directory` is a parameter? That could also be a variable in this template, right? Or is this directory used elsewhere outside this stage?

2023-10-04 15:58 UTC, mmsmits commented on scanBinaries.yml
> +  directory: # directory where the zipfile is extracted
Ah you are right, we can just call it "binaries" or something common

2023-10-04 16:04 UTC, marcovisserFurore requested changes
Some errors now because of the new variable.

2023-10-04 16:04 UTC, marcovisserFurore commented on scanBinaries.yml
> +        destinationFolder: ${{ parameters.directory }}
This is not going to work. You have to change this to the new variable.

2023-10-04 16:04 UTC, marcovisserFurore commented on scanBinaries.yml
> +        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -v ${{ parameters.directory }}:/src  aquasec/trivy:latest  --exit-code 1 --format table --scanners vuln,config,secret
Same here

2023-10-04 16:09 UTC, marcovisserFurore requested changes

2023-10-04 16:09 UTC, marcovisserFurore commented on scanBinaries.yml
> +        destinationFolder: ${{ parameters.directory }}
So `$(directory)`. See also [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline).

2023-10-05 08:48 UTC, marcovisserFurore approved these changes

2023-10-05 08:49 UTC, merged