Refactoring to allow ignore file in all trivy scan
FirelyTeam/azure-pipeline-templates pull request #32
Opened 2024-10-09 11:53 UTC by louisledev

2024-10-09 14:53 UTC, cknaap requested changes

2024-10-09 14:53 UTC, cknaap commented on scanBinaries.yml
> +  trivyIgnoreFile: '' # path to the trivy ignore file
Why do the parameters in this file not have the type, default and displayName specified, like in scanCompiledArtifacts.yml and in scanDockerImage.yml?

2024-10-09 14:53 UTC, cknaap commented on scanWithRetryTask.yml
> +      mountArgs="-v /tmp:/tmp"
why do you need to mount `/tmp` here?

2024-10-09 15:39 UTC, louisledev commented on scanWithRetryTask.yml
> +      mountArgs="-v /tmp:/tmp"
Well, no bertter answer that this is how this was before. I looked into the doc, and could not see any reason, so removed it, will see if this works.

2024-10-09 15:40 UTC, louisledev commented on scanBinaries.yml
> +  trivyIgnoreFile: '' # path to the trivy ignore file
No better answer that usually we don't provide the name, type, display and default value in our templates, but this seems to be a good practice, so let's start.

2024-10-10 07:18 UTC, cknaap approved these changes

2024-10-10 07:58 UTC, merged