Adding task to retain build if this is a release
FirelyTeam/azure-pipeline-templates pull request #33
Opened 2024-11-06 12:38 UTC by louisledev

2024-11-07 12:23 UTC, mmsmits requested changes

2024-11-07 12:36 UTC, louisledev commented on retainReleaseBuild.yml
> +      $isReleaseTag = $($env:BUILD_SOURCEBRANCH -like 'refs/tags/v*')
My initial idea was to have a template retainBuild.yml, with a parameter regarding the duration.
However, I struggled to achieve that, mostly because I could not use a condition when calling the template and because using the `${{ if ..}}` syntax would not work as this was evaluated at compile time.

Thinking about your suggestion, and based on this https://stackoverflow.com/questions/65327540/how-to-pass-variables-to-templates-for-task-conditions-in-yaml-pipeline, I am thinking about adding a generic `condition` as parameter, and leave the caller to set the condition. In most case, something like `isReleaseTag and succeeded()`...
What do you think?

2024-11-07 13:55 UTC, mmsmits commented on retainReleaseBuild.yml
> +      $isReleaseTag = $($env:BUILD_SOURCEBRANCH -like 'refs/tags/v*')
That woud be nice!

2024-11-08 10:03 UTC, mmsmits approved these changes

2024-11-08 10:04 UTC, merged

2024-11-08 10:04 UTC, mmsmits commented
Very nice with the condition!